services:
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
      target: data-quality-simulator
    image: data-quality-simulator
    environment:
      LOGGER_LEVEL: ${SIMULATOR_LOGGER_LEVEL:-info}
    depends_on:
      db:
        condition: service_completed_successfully
    command:
      [
        "--config-file-path=${SIMULATOR_CONFIG_FILE_PATH:-config-files/base_config.json}"
      ]
    volumes:
      - ./config-files:/app/config-files
      - ./datasets:/app/datasets
      - ./db/data:/app/db

  db:
    image: keinos/sqlite3:3.46.0
    working_dir: /db
    user: "${uid:-1000}:${gid:-1000}"
    group_add:
      - sqlite
    volumes:
      - ./db/init/seed.sql:/initdb.d/seed.sql
      - ./db/data:/db
    command:
      [
        "sh",
        "-c",
        "cat /initdb.d/seed.sql | sqlite3 simulations.db && chmod 666 simulations.db"
      ]

  # https://stackoverflow.com/q/51120204/5587393
  notebook:
    build:
      dockerfile_inline: |
        FROM quay.io/jupyter/base-notebook:latest
        RUN pip install pandas==2.2.2 matplotlib==3.9.0
    image: notebook
    container_name: jupyter-notebook
    user: "${uid:-1000}:${gid:-1000}"
    group_add:
      - users
    ports:
      - 8889:8888
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./db/data:/home/jovyan/db:ro
    command: start-notebook.py --NotebookApp.token='my-token'

  get-results:
    image: keinos/sqlite3:3.46.0
    working_dir: /db
    volumes:
      - ./db/data:/db:ro
    command:
      [
        "sh",
        "-c",
        "printf \".mode markdown

          select * from results;\" | sqlite3 simulations.db"
      ]

  count-results:
    image: keinos/sqlite3:3.46.0
    working_dir: /db
    volumes:
      - ./db/data:/db:ro
    command:
      [
        "sh",
        "-c",
        "echo \"select count(*) from results;\" | sqlite3 simulations.db"
      ]

  delete-all:
    image: keinos/sqlite3:3.46.0
    working_dir: /db
    user: "${uid:-1000}:${gid:-1000}"
    volumes:
      - ./db/data:/db
    command:
      [
        "sh",
        "-c",
        "echo \"delete from results;\" | sqlite3 simulations.db"
      ]

  run-query:
    image: keinos/sqlite3:3.46.0
    working_dir: /db
    user: "${uid:-1000}:${gid:-1000}"
    volumes:
      - ./db/data:/db
    command:
      [
        "sh",
        "-c",
        "echo \"${SQL_CODE}\" | sqlite3 simulations.db"
      ]
