apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Release.Name }}-simulation-job-
{{ include "simulation.metadata" . | indent 2 }}
spec:
  backoffLimit: 0
  template:
    metadata:
{{ include "simulation.metadata" . | indent 6 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: create-db-if-not-exists
          image: keinos/sqlite3:3.48.0
          workingDir: /db
          volumeMounts:
            - name: init-db-volume
              mountPath: /initdb.d
              readOnly: true
            - name: db-data-volume
              mountPath: /db
          command:
            ["sh", "-c", "cat /initdb.d/seed.sql | sqlite3 simulations.db"]
      containers:
        - name: simulator
          image: bash:latest
          # image: maluz/data-quality-simulator:1.0.0
          workingDir: /app
          args: ["sleep", "3600"]
          volumeMounts:
            - name: db-data-volume
              mountPath: /app/db
            - name: datasets-volume
              mountPath: /app/datasets
      restartPolicy: Never
      volumes:
        - name: db-data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.databaseVolumeClaimName }}
        - name: datasets-volume
          persistentVolumeClaim:
            claimName: {{ .Values.datasetsVolumeClaimName }}
        - name: init-db-volume
          configMap:
            name: {{ .Values.dbInitConfigMap }}
